DROP TABLE IF EXISTS `pistar_model`;

CREATE TABLE `pistar_model` (
  `HASH` UUID NOT NULL,
  `JSON_CONTENT` LONGTEXT NOT NULL,
  `REMOTE_ADDR` LONGTEXT NOT NULL,
  `INSERTED_DATE` TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (`hash`)
) DEFAULT CHARSET=utf8;

